### ISSUE TITLE
how to complete list of chat with getdialogs???

### ISSUE THREAD

**Issue by Ansel1234S** [steavy29/Telegram.Net#22]
how to complete list of chat with getdialogs???

**Comment by Ansel1234S** [comment]
i use get dialog Method . My Telegram Account Has More Than 350 Groups,I want to get All Chats,But That's Method Can Not Give All Chat, sometimes Get 120 Chats, Sometimes 125 Chats, No more than 350 Chats, Please Example Method For Resolve My Problem. Thank you

**Comment by steavy29** [comment]
Hm, interesting. Then I assume there is some limit, how many dialogs you can load in one request(though I didn't see anything like this in documentation). I suggest you to load your dialogs in two requests then using `offset` parameter. Unfortunately I can't try this on my own, because I don't an account with so many dialogs.

**Comment by steavy29** [comment]
Closing the issue since there is no further feedback from the OP
